"""record the venue a tour registration is for

Revision ID: 12a105423ba9
Revises: 1f0b18dbe9a0
Create Date: 2026-08-12 09:27:20.903047
"""

from alembic import op
import sqlalchemy as sa


revision = '12a105423ba9'
down_revision = '1f0b18dbe9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_registrations_venue_id'), ['venue_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_event_registrations_venue_id_venues'), 'venues', ['venue_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_registrations_venue_id_venues'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_registrations_venue_id'))
        batch_op.drop_column('venue_id')

    # ### end Alembic commands ###
