"""initial schema

Revision ID: b33b66a6a6bc
Revises: 
Create Date: 2026-08-02 11:55:55.445894
"""

from alembic import op
import sqlalchemy as sa


revision = 'b33b66a6a6bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('category_slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_categories')),
    sa.UniqueConstraint('category_slug', name=op.f('uq_article_categories_category_slug'))
    )
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_tags')),
    sa.UniqueConstraint('tag', name=op.f('uq_article_tags_tag'))
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('cdn_url', sa.String(length=512), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index(op.f('ix_media_assets_owner_id'), 'media_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_assets_owner_type'), 'media_assets', ['owner_type'], unique=False)
    op.create_table('promotion_popups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('title_id', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('body_id', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.String(length=1024), nullable=True),
    sa.Column('banner_key', sa.String(length=1024), nullable=True),
    sa.Column('cta_label_id', sa.String(length=120), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_url', sa.String(length=1024), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_popups'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('showcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title_id', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('body_id', sa.Text(), nullable=True),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('showcase_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('image_storage_key', sa.String(length=512), nullable=True),
    sa.Column('image_variants', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_showcases_showcase_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_showcases')),
    sa.UniqueConstraint('public_id', name=op.f('uq_showcases_public_id')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_showcases_source_ref'))
    )
    op.create_index(op.f('ix_showcases_showcase_date'), 'showcases', ['showcase_date'], unique=False)
    op.create_index(op.f('ix_showcases_slug'), 'showcases', ['slug'], unique=True)
    op.create_index(op.f('ix_showcases_status'), 'showcases', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('price_start_from', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_for_total_pax', sa.Integer(), nullable=False),
    sa.Column('ballrooms', sa.JSON(), nullable=True),
    sa.Column('packages', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name=op.f('ck_venues_venue_status_allowed')),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name=op.f('ck_venues_venue_stars_between_1_and_5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('city', 'slug', name='uq_venues_city_slug'),
    sa.UniqueConstraint('public_id', name=op.f('uq_venues_public_id'))
    )
    op.create_index(op.f('ix_venues_city'), 'venues', ['city'], unique=False)
    op.create_index(op.f('ix_venues_status'), 'venues', ['status'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary_id', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('body_id', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('image_caption', sa.String(length=255), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('schema_jsonld', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trash', sa.Boolean(), nullable=False),
    sa.Column('topic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name=op.f('ck_articles_article_status_allowed')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_articles_author_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], name=op.f('fk_articles_category_id_article_categories')),
    sa.ForeignKeyConstraint(['image_asset_id'], ['media_assets.id'], name=op.f('fk_articles_image_asset_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('category_id', 'slug', name='uq_articles_category_slug'),
    sa.UniqueConstraint('public_id', name=op.f('uq_articles_public_id'))
    )
    op.create_index(op.f('ix_articles_author_id'), 'articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_articles_category_id'), 'articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_trash'), 'articles', ['trash'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('contact_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_contact_leads_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_leads'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_table('venue_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('temp_venue_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('cdn_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('original_width', sa.Integer(), nullable=True),
    sa.Column('original_height', sa.Integer(), nullable=True),
    sa.Column('original_file_size', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('webp_srcset', sa.Text(), nullable=True),
    sa.Column('jpeg_srcset', sa.Text(), nullable=True),
    sa.Column('sizes_attribute', sa.Text(), nullable=True),
    sa.Column('breakpoints_used', sa.JSON(), nullable=True),
    sa.Column('formats_generated', sa.JSON(), nullable=True),
    sa.Column('webp_variants', sa.JSON(), nullable=True),
    sa.Column('jpeg_variants', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_venue_photos_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue_photos')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_venue_photos_storage_key'))
    )
    op.create_table('venue_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('packages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_venue_translations_venue_id_venues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue_translations')),
    sa.UniqueConstraint('venue_id', 'locale', name='uq_venue_translations_venue_locale')
    )
    op.create_index(op.f('ix_venue_translations_locale'), 'venue_translations', ['locale'], unique=False)
    op.create_index(op.f('ix_venue_translations_venue_id'), 'venue_translations', ['venue_id'], unique=False)
    op.create_table('article_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('temp_article_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_hash', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('cdn_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_images_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_article_images_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_images'))
    )
    op.create_index(op.f('ix_article_images_file_hash'), 'article_images', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_images_file_hash'), table_name='article_images')
    op.drop_table('article_images')
    op.drop_index(op.f('ix_venue_translations_venue_id'), table_name='venue_translations')
    op.drop_index(op.f('ix_venue_translations_locale'), table_name='venue_translations')
    op.drop_table('venue_translations')
    op.drop_table('venue_photos')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('contact_leads')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_articles_trash'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_author_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_venues_status'), table_name='venues')
    op.drop_index(op.f('ix_venues_city'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_showcases_status'), table_name='showcases')
    op.drop_index(op.f('ix_showcases_slug'), table_name='showcases')
    op.drop_index(op.f('ix_showcases_showcase_date'), table_name='showcases')
    op.drop_table('showcases')
    op.drop_table('roles')
    op.drop_table('promotion_popups')
    op.drop_index(op.f('ix_media_assets_owner_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_owner_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('article_tags')
    op.drop_table('article_categories')
    # ### end Alembic commands ###
