"""branches and events

Revision ID: c3683869fcd8
Revises: c14e2f7a91d3
Create Date: 2026-08-11 13:19:48.354827
"""

import uuid
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa


revision = 'c3683869fcd8'
down_revision = 'c14e2f7a91d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('public_phone', sa.String(length=40), nullable=True),
    sa.Column('public_email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=40), nullable=True),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('bookable', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('public_id', name=op.f('uq_branches_public_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_branches_slug'))
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_city'), ['city'], unique=False)

    op.create_table('branch_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('starts_at_local', sa.DateTime(), nullable=False),
    sa.Column('ends_at_local', sa.DateTime(), nullable=False),
    sa.Column('full_day', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('public_label', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_closures_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_closures'))
    )
    with op.batch_alter_table('branch_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_closures_branch_id'), ['branch_id'], unique=False)

    op.create_table('branch_opening_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at_local', sa.Time(), nullable=False),
    sa.Column('closes_at_local', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_opening_hours_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_opening_hours'))
    )
    with op.batch_alter_table('branch_opening_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_opening_hours_branch_id'), ['branch_id'], unique=False)

    op.create_table('branch_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('sender_display_name', sa.String(length=150), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('tour_notification_recipients', sa.JSON(), nullable=False),
    sa.Column('tour_intro_html', sa.Text(), nullable=True),
    sa.Column('arrival_instructions', sa.Text(), nullable=True),
    sa.Column('parking_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_branch_settings_branch_id_branches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_settings')),
    sa.UniqueConstraint('branch_id', name=op.f('uq_branch_settings_branch_id'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=False),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('event_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_events_branch_id_branches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('public_id', name=op.f('uq_events_public_id'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_branch_id'), ['branch_id'], unique=False)

    op.create_table('event_email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_email_templates_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_email_templates')),
    sa.UniqueConstraint('event_id', 'kind', name='uq_event_email_templates_event_id_kind')
    )
    with op.batch_alter_table('event_email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_email_templates_event_id'), ['event_id'], unique=False)

    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('visit_slot', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('follow_up', sa.Boolean(), nullable=False),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_registrations_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_registrations')),
    sa.UniqueConstraint('public_id', name=op.f('uq_event_registrations_public_id'))
    )
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registrations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_registrations_status'), ['status'], unique=False)

    op.create_table('event_registration_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['event_registrations.id'], name=op.f('fk_event_registration_guests_registration_id_event_registrations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_registration_guests'))
    )
    with op.batch_alter_table('event_registration_guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registration_guests_registration_id'), ['registration_id'], unique=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_roles_user_role'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_roles_branch_id'), ['branch_id'], unique=False)
        batch_op.create_unique_constraint('uq_user_roles_user_role_branch', ['user_id', 'role_id', 'branch_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_roles_branch_id_branches'), 'branches', ['branch_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

    # A default branch so /tour resolves on day one. Existing role rows already
    # have branch_id NULL, which means org-wide -- today's admins keep full access
    # with no backfill needed.
    # created_at is passed explicitly rather than left to its server default.
    # SQLite accepts DEFAULT now() in the CREATE TABLE but has no now() function
    # to evaluate on INSERT, so relying on the default breaks the dev database.
    seeded_at = datetime.now(UTC)
    branches = sa.table(
        "branches",
        sa.column("id", sa.Integer),
        sa.column("public_id", sa.Uuid),
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("address_line1", sa.String),
        sa.column("city", sa.String),
        sa.column("country_code", sa.String),
        sa.column("timezone", sa.String),
        sa.column("active", sa.Boolean),
        sa.column("bookable", sa.Boolean),
        sa.column("is_default", sa.Boolean),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        branches,
        [
            {
                "public_id": uuid.uuid4(),
                "slug": "jakarta",
                "name": "7Magic Jakarta",
                "address_line1": "",
                "city": "jakarta",
                "country_code": "ID",
                "timezone": "Asia/Jakarta",
                "active": True,
                "bookable": True,
                "is_default": True,
                "created_at": seeded_at,
            }
        ],
    )
    connection = op.get_bind()
    branch_id = connection.execute(
        sa.text("SELECT id FROM branches WHERE slug = 'jakarta'")
    ).scalar_one()
    op.bulk_insert(
        sa.table(
            "branch_settings",
            sa.column("branch_id", sa.Integer),
            sa.column("tour_notification_recipients", sa.JSON),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "branch_id": branch_id,
                "tour_notification_recipients": [],
                "created_at": seeded_at,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_roles_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint('uq_user_roles_user_role_branch', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_roles_branch_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_roles_user_role'), ['user_id', 'role_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('event_registration_guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registration_guests_registration_id'))

    op.drop_table('event_registration_guests')
    with op.batch_alter_table('event_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_registrations_email'))

    op.drop_table('event_registrations')
    with op.batch_alter_table('event_email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_email_templates_event_id'))

    op.drop_table('event_email_templates')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_branch_id'))

    op.drop_table('events')
    op.drop_table('branch_settings')
    with op.batch_alter_table('branch_opening_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_opening_hours_branch_id'))

    op.drop_table('branch_opening_hours')
    with op.batch_alter_table('branch_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_closures_branch_id'))

    op.drop_table('branch_closures')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_city'))

    op.drop_table('branches')
    # ### end Alembic commands ###
